import * as Joi from 'joi';

export const configurationValidate = Joi.object({
  PORT: Joi.number().required(),
  BASE_APP_URL: Joi.string().required(),
  FRONTEND_URL: Joi.string().required(),
  NODE_ENV: Joi.string().required(),
  DB_HOST: Joi.string().required(),
  DB_PORT: Joi.number().required(),
  DB_USERNAME: Joi.string().required(),
  DB_PASSWORD: Joi.string().required(),
  DB_NAME: Joi.string().required(),
  SONAR_SERVER_URL: Joi.string().required(),
  SONAR_TOKEN: Joi.string().required(),
  AUTH0_DOMAIN: Joi.string().required(),
  AUTH0_CLIENT_ID: Joi.string().required(),
  AUTH0_CLIENT_SECRET: Joi.string().required(),
  AUTH0_AUDIENCE: Joi.string().required(),
  JWT_PROVIDER_PREFIX: Joi.string().required(),
  STELLAR_SERVER_URL: Joi.string().required(),
  STELLAR_NETWORK_PASSPHRASE: Joi.string().required(),
  STELLAR_ISSUER_PUBLIC_KEY: Joi.string().required(),
  STELLAR_ISSUER_SECRET_KEY: Joi.string().required(),
  STELLAR_DISTRIBUTOR_PUBLIC_KEY: Joi.string().required(),
  STELLAR_DISTRIBUTOR_SECRET_KEY: Joi.string().required(),
  SOROBAN_SERVER_URL: Joi.string().required(),
  SOROBAN_CONTRACT_ADDRESS: Joi.string().required(),
});
