interface IRPAProps {
	projectName: string;
	issuerName: string;
	spvName: string;
	tokenSymbol: string;
	tokenSupply: number;
	tokenPrice: number;
	distributionFrequency: string;
	governingState: string;
}

const RevenueParticipationAgreement = ({
	projectName,
	issuerName,
	spvName,
	tokenSymbol,
	tokenSupply,
	tokenPrice,
	distributionFrequency,
	governingState,
}: IRPAProps) => {
	return (
		<div className="max-h-[260px] overflow-y-auto rounded-xl border border-[#E5E7EB] bg-[#F9FAFB] p-4 text-sm leading-6 text-[#374151]">
			<h3 className="mb-3 text-base font-semibold text-[#111827]">
				Revenue Participation Agreement (RPA)
			</h3>

			<p>
				This Revenue Participation Agreement relates to the project{' '}
				<strong>{projectName}</strong>, issued by <strong>{issuerName}</strong>{' '}
				and operated via <strong>{spvName}</strong>.
			</p>

			<p className="mt-3">
				By purchasing <strong>{tokenSymbol}</strong> tokens, you acquire a
				contractual right to receive a proportional share of future cashflows
				generated by the project.
			</p>

			<p className="mt-3">
				A total of <strong>{tokenSupply.toLocaleString()}</strong> tokens have
				been issued at a price of{' '}
				<strong>${tokenPrice.toLocaleString()}</strong> per token.
			</p>

			<p className="mt-3">Your economic entitlement is calculated as:</p>

			<p className="mt-2 font-medium">
				(Tokens Held ÷ {tokenSupply.toLocaleString()}) × Distributable Cashflows
			</p>

			<p className="mt-3">
				Distributions are expected to occur on a{' '}
				<strong>{distributionFrequency}</strong> basis.
			</p>

			<p className="mt-3">
				Project revenues may include energy sales (PPAs), wholesale market
				participation, battery arbitrage, and environmental credits.
			</p>

			<p className="mt-3">
				The project is structured under a Managed Investment Scheme (MIS), which
				governs asset ownership, operations, and cashflow management.
			</p>

			<p className="mt-3">
				Tokens represent a contractual economic interest only and do not provide
				direct ownership of the underlying assets.
			</p>

			<p className="mt-3">
				Returns are not guaranteed. This investment may be illiquid and subject
				to market, operational, and regulatory risks.
			</p>

			<p className="mt-3">
				By proceeding, you agree to be bound by this agreement and all
				project-specific documentation.
			</p>

			<p className="mt-3 text-xs text-gray-500">
				Governing law: {governingState}, Australia
			</p>
		</div>
	);
};

export default RevenueParticipationAgreement;
