export const REGENX_TIPS = [
	'Investments structured via SPVs or managed investment schemes.',
	'Tokens represent economic interests, not legal ownership.',
	'Legal ownership maintained by trustee or registry.',
	'Custody handled by Fireblocks or Zodia.',
	'Investors typically do not control private keys.',
	'Returns depend on asset performance, not token price.',
	'Revenue from energy sales, PPAs, or grid services.',
	'Distributions follow costs, fees, then investor returns.',
	'Liquidity is not guaranteed.',
	'Transfers may require investor eligibility checks.',
	'Investments are typically long-term.',
	'Battery systems generate value through optimisation.',
	'Solar projects rely on contracted revenue.',
	'Projects may combine multiple revenue streams.',
	'Real-time data shows asset performance.',
	'Platform data does not replace legal documents.',
	'Development projects carry higher risk.',
	'Operating assets may provide stable cashflows.',
	'Blockchain used for settlement, not registry.',
	'Custody providers manage transaction security.',
	'Secondary trading depends on platform rules.',
	'Investor eligibility may be restricted.',
	'Project structure defines investor rights.',
	'Always review offering documents before investing.',
];
